server.port=8080
spring.application.name=market-analysis
spring.jackson.property-naming-strategy=SNAKE_CASE
ml.model.url=http://localhost:8000
spring.cache.type=caffeine
spring.cache.caffeine.spec=expireAfterWrite=3600s
